Commenter
Signed-off-by: apostasie <spam_blackhole@farcloser.world>

diff --git a/.github/workflows/job-test-in-container.yml b/.github/workflows/job-test-in-container.yml
--- a/.github/workflows/job-test-in-container.yml
+++ b/.github/workflows/job-test-in-container.yml
@@ -35,6 +35,10 @@ on:
         required: false
         default: false
         type: boolean
+    outputs:
+      artifact:
+        description: "Artifact generated by this job"
+        value: ${{ jobs.test.outputs.artifact }}
 
 env:
   GOTOOLCHAIN: local
@@ -55,6 +59,8 @@ jobs:
     defaults:
       run:
         shell: bash
+    outputs:
+      artifact: ${{ steps.artifact-upload.outputs.artifact-url }}
 
     env:
       # https://github.com/containerd/nerdctl/issues/622
@@ -158,12 +164,12 @@ jobs:
           # Besides, each job is running on a different instance, which means using host network here
           # is safe and has no side effects on others.
           [ "${{ inputs.target }}" == "rootful" ] \
-            && args=(test-integration ./hack/test-integration.sh -test.allow-modify-users=true) \
-            || args=(test-integration-${{ inputs.target }} /test-integration-rootless.sh ./hack/test-integration.sh)
+            && args=(test-integration ./hack/testing/integration.sh -test.allow-modify-users=true) \
+            || args=(test-integration-${{ inputs.target }} /test-integration-rootless.sh ./hack/testing/integration.sh)
           if [ "${{ inputs.ipv6 }}" == true ]; then
-            docker run --network host -t --rm --privileged -e GITHUB_STEP_SUMMARY="$GITHUB_STEP_SUMMARY" -v "$GITHUB_STEP_SUMMARY":"$GITHUB_STEP_SUMMARY" -e WORKAROUND_ISSUE_622=${WORKAROUND_ISSUE_622:-} "${args[@]}" -test.only-flaky=false -test.only-ipv6 -test.target=${{ inputs.binary }}
+            docker run --name test-runner --network host -t --privileged -e GITHUB_STEP_SUMMARY="$GITHUB_STEP_SUMMARY" -v "$GITHUB_STEP_SUMMARY":"$GITHUB_STEP_SUMMARY" -e WORKAROUND_ISSUE_622=${WORKAROUND_ISSUE_622:-} "${args[@]}" -test.only-flaky=false -test.only-ipv6 -test.target=${{ inputs.binary }}
           else
-            docker run -t --rm --privileged -e GITHUB_STEP_SUMMARY="$GITHUB_STEP_SUMMARY" -v "$GITHUB_STEP_SUMMARY":"$GITHUB_STEP_SUMMARY" -e WORKAROUND_ISSUE_622=${WORKAROUND_ISSUE_622:-} "${args[@]}" -test.only-flaky=false -test.target=${{ inputs.binary }}
+            docker run --name test-runner -t --privileged -e GITHUB_STEP_SUMMARY="$GITHUB_STEP_SUMMARY" -v "$GITHUB_STEP_SUMMARY":"$GITHUB_STEP_SUMMARY" -e WORKAROUND_ISSUE_622=${WORKAROUND_ISSUE_622:-} "${args[@]}" -test.only-flaky=false -test.target=${{ inputs.binary }}
           fi
       # FIXME: this NEEDS to go away
       - name: "Run: integration tests (flaky)"
@@ -172,18 +178,94 @@ jobs:
           github::md::h2 "flaky" >> "$GITHUB_STEP_SUMMARY"
 
           [ "${{ inputs.target }}" == "rootful" ] \
-            && args=(test-integration ./hack/test-integration.sh) \
-            || args=(test-integration-${{ inputs.target }} /test-integration-rootless.sh ./hack/test-integration.sh)
+            && args=(test-integration ./hack/testing/integration.sh) \
+            || args=(test-integration-${{ inputs.target }} /test-integration-rootless.sh ./hack/testing/integration.sh)
           if [ "${{ inputs.ipv6 }}" == true ]; then
-            docker run --network host -t --rm --privileged -e GITHUB_STEP_SUMMARY="$GITHUB_STEP_SUMMARY" -v "$GITHUB_STEP_SUMMARY":"$GITHUB_STEP_SUMMARY" -e WORKAROUND_ISSUE_622=${WORKAROUND_ISSUE_622:-} "${args[@]}" -test.only-flaky=true -test.only-ipv6 -test.target=${{ inputs.binary }}
+            docker run --name test-runner-flaky --network host -t --privileged -e GITHUB_STEP_SUMMARY="$GITHUB_STEP_SUMMARY" -v "$GITHUB_STEP_SUMMARY":"$GITHUB_STEP_SUMMARY" -e WORKAROUND_ISSUE_622=${WORKAROUND_ISSUE_622:-} "${args[@]}" -test.only-flaky=true -test.only-ipv6 -test.target=${{ inputs.binary }}
           else
-            docker run -t --rm --privileged -e GITHUB_STEP_SUMMARY="$GITHUB_STEP_SUMMARY" -v "$GITHUB_STEP_SUMMARY":"$GITHUB_STEP_SUMMARY" -e WORKAROUND_ISSUE_622=${WORKAROUND_ISSUE_622:-} "${args[@]}" -test.only-flaky=true -test.target=${{ inputs.binary }}
+            docker run --name test-runner-flaky -t --privileged -e GITHUB_STEP_SUMMARY="$GITHUB_STEP_SUMMARY" -v "$GITHUB_STEP_SUMMARY":"$GITHUB_STEP_SUMMARY" -e WORKAROUND_ISSUE_622=${WORKAROUND_ISSUE_622:-} "${args[@]}" -test.only-flaky=true -test.target=${{ inputs.binary }}
           fi
 
-      - name: Logs
-        if: ${{ failure() }}
+      - name: "Wrap: collect logs"
+        if: ${{ failure() || success() }}
+        run: |
+          # Get the reports from inside the containers
+          [ "${{ inputs.target }}" == "rootful" ] && src=/root || src=/home/rootless
+          mkdir -p ~/report
+          docker cp test-runner:$src/nerdctl-test-report ~/report/main || true
+          # Flaky may not have run
+          docker cp test-runner-flaky:$src/nerdctl-test-report ~/report/flaky 2>/dev/null || true
+
+      - name: "Wrap: upload artifact"
+        id: artifact-upload
+        if: ${{ failure() || success() }}
         uses: actions/upload-artifact@v4
         with:
-          name: "System logs"
-          path: ~/debug-logs.tar.gz
+          path: ~/report/*
           retention-days: 1
+#          name: logs-${{ inputs.binary }}-${{ inputs.target }}-${{ inputs.runner }}-${{ inputs.ipv6 }}-${{ inputs.canary }}-${{ inputs.containerd-version }}-${{ inputs.rootlesskit-version }}
+
+#      - name: Annotate
+#        if: ${{ failure() || success() }}
+#        run: |
+#          echo "::add-matcher::.github/matchers/tigron.json"
+#          echo "::error title=ErrorReport::MEH .github/workflows/job-test-in-host.yml${{steps.artifact-upload.outputs.artifact-url}}"
+#          echo "::notice title=NoticeReport::SHEESH ${{steps.artifact-upload.outputs.artifact-url}}"
+#          echo "::error file=cmd/nerdctl/main_test_test.go,line=1,endLine=10,title=AgainErrorReport::FOO ${{steps.artifact-upload.outputs.artifact-url}}"
+#          echo "::error file=cmd/nerdctl/main_test.go,line=38,endLine=41,title=AgainErrorReport::BLA ${{steps.artifact-upload.outputs.artifact-url}}"
+#          echo "Error: TestFooFoo "
+#          pwd
+#          ls -lA cmd/nerdctl/main_test_test.go || true
+#          # ::workflow-command parameter1={data},parameter2={data}::{command value}
+#          echo "::remove-matcher owner=tigron::"
+#
+# GITHUB_RUN_ATTEMPT
+# GITHUB_RUN_ID
+# GITHUB_RUN_NUMBER
+# GITHUB_SHA
+
+
+#      - name: "Comment report"
+#        if: ${{ failure() }}
+#        uses: ./.github/actions/wax
+#        with:
+#          body: "body test (in-container)"
+#          github-token: ${{ secrets.GITHUB_TOKEN }}
+# steps.artifact-upload.outputs.artifact-url
+
+#      - name:  Commenting
+#        if: ${{ failure() || success() }}
+#        uses: actions/github-script@v7
+#        with:
+#          github-token: ${{ secrets.GITHUB_TOKEN }}
+#          script: |
+#            let comments = await github.rest.issues.listComments({
+#              issue_number: context.issue.number,
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#            })
+#
+#            let found = 0
+#            let body = ""
+#            comments.data.forEach(function(comment){
+#              if (comment.user.login === context.repo.login) {
+#                found = comment.id
+#                body = comment.body
+#              }
+#            })
+#
+#            if (found === 0){
+#              github.rest.issues.createComment({
+#                issue_number: context.issue.number,
+#                owner: context.repo.owner,
+#                repo: context.repo.repo,
+#                body: "${{steps.artifact-upload.outputs.artifact-url}}\n"
+#              })
+#            }else{
+#              github.rest.issues.updateComment({
+#                comment_id: found,
+#                owner: context.repo.owner,
+#                repo: context.repo.repo,
+#                body: body + "${{steps.artifact-upload.outputs.artifact-url}}\n"
+#              })
+#            }
