Fix alma ci target
Signed-off-by: apostasie <spam_blackhole@farcloser.world>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -429,6 +429,10 @@ jobs:
       matrix:
         mode: ["rootful", "rootless"]
     runs-on: ubuntu-24.04
+    env:
+      MODE: ${{ matrix.mode }}
+      # FIXME: this is only necessary to access the build cache. To remove with build cleanup.
+      CONTAINERD_VERSION: v2.0.3
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
         with:
@@ -490,20 +494,44 @@ jobs:
           echo "DOCKER_HOST=${DOCKER_HOST}" >>$GITHUB_ENV
           docker info
           docker version
+      - name: "Expose GitHub Runtime variables for gha"
+        uses: crazy-max/ghaction-github-runtime@b3a9207c0e1ef41f4cf215303c976869d0c2c1c4  # v3.0.0
       - name: "Prepare integration tests"
-        env:
-          MODE: ${{ matrix.mode }}
         run: |
           set -eux
-          TARGET=test-integration
-          [ "$MODE" = "rootless" ] && TARGET=test-integration-rootless
-          docker build -t test-integration --target "${TARGET}" .
-          # losetup not working as expected on EL8?
-          # > === FAIL: cmd/nerdctl/container TestRunDevice (0.44s)
-          # > container_run_cgroup_linux_test.go:236: assertion failed: error is not nil: loopback setup failed ([losetup --find --show /tmp/containerd-test-loopback3931357228]):
-          # > stdout="", stderr="losetup: /tmp/containerd-test-loopback3931357228: failed to set up loop device: No such file or directory\n": exit status 1
-          # https://github.com/containerd/nerdctl/pull/3904#issuecomment-2670917820
+
           sudo losetup -Dv
           sudo losetup -lv
+
+          TARGET=test-integration
+          [ "$MODE" = "rootless" ] && TARGET=test-integration-rootless
+          docker buildx create --name with-gha --use
+          docker buildx build \
+            --output=type=docker \
+            --cache-from type=gha,scope=amd64-${CONTAINERD_VERSION} \
+            -t test-integration --target "${TARGET}" \
+            .
+
       - name: "Run integration tests"
-        run: docker run -t --rm --privileged test-integration
+        # Presumably, something is broken with the way docker exposes /dev to the container, as it appears to only
+        # randomly work. Mounting /dev does workaround the issue.
+        # This might be due to the old kernel shipped with Alma (4.18), or something else between centos/docker.
+        run: |
+          set -eux
+          [ "$MODE" = "rootless" ] && {
+            echo "rootless"
+            docker run -t -v /dev:/dev --rm --privileged test-integration /test-integration-rootless.sh ./hack/test-integration.sh -test.only-flaky=false
+          } || {
+            echo "rootful"
+            docker run -t -v /dev:/dev --rm --privileged test-integration ./hack/test-integration.sh -test.only-flaky=false
+          }
+      - name: "Run integration tests (flaky)"
+        run: |
+          set -eux
+          [ "$MODE" = "rootless" ] && {
+            echo "rootless"
+            docker run -t -v /dev:/dev --rm --privileged test-integration /test-integration-rootless.sh ./hack/test-integration.sh -test.only-flaky=true
+          } || {
+            echo "rootful"
+            docker run -t -v /dev:/dev --rm --privileged test-integration ./hack/test-integration.sh -test.only-flaky=true
+          }
